name: Build Custom Clonezilla Live

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow launch manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cache apt packages
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/package-list.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      # 3. Cache downloaded rootfs or other heavy files
      - name: Cache ISO rootfs
        uses: actions/cache@v3
        with:
          path: rootfs_cache
          key: ${{ runner.os }}-rootfs-${{ hashFiles('**/rootfs-dependencies.txt') }}
          restore-keys: |
            ${{ runner.os }}-rootfs-

      # 4. Install dependencies (apt)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap xorriso isolinux libarchive-tools

      # 5. Extract Clonezilla ISO
      - name: Extract Clonezilla ISO
        run: |
          mkdir iso_root
          bsdtar -C iso_root -xf clonezilla.iso


      # 6. Build ISO
      - name: Build ISO
        run: |
          ./build-iso.sh

