name: Build Custom Clonezilla Live

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t clonezilla-builder .
    
    - name: Build custom ISO
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -e GITHUB_WORKSPACE=/workspace \
          clonezilla-builder
    
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: hardclone-live-iso
        path: "*.iso"
        retention-days: 30
    
    - name: Release (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: "*.iso"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
