name: Build Custom Clonezilla Live

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow launch manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cache apt packages
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/package-list.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      # 3. Cache downloaded rootfs or other heavy files
      - name: Cache ISO rootfs
        uses: actions/cache@v3
        with:
          path: rootfs_cache
          key: ${{ runner.os }}-rootfs-${{ hashFiles('**/rootfs-dependencies.txt') }}
          restore-keys: |
            ${{ runner.os }}-rootfs-

      # 4. Install dependencies (apt)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap xorriso isolinux

      # 5. Prepare root filesystem (can be cached)
      - name: Prepare root filesystem
        run: |
          mkdir -p rootfs_cache
          if [ ! -f rootfs_cache/prepared.txt ]; then
            ./prepare-rootfs.sh  # Script to create rootfs
            touch rootfs_cache/prepared.txt
          else
            echo "Using cached root filesystem"
          fi

      # 6. Build ISO
      - name: Build ISO
        run: |
          ./build-iso.sh

